/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Art_bor (https://sketchfab.com/Art_bor)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/potato-pc-69f0bf39801e4fdf83bf584896935859
Title: Potato Pc
*/

import { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import potatoScene from '../assets/3d/potato.glb';

const Potato = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(potatoScene);
  const { actions } = useAnimations(animations, group);
  return (
    <a.group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_136">
                <group name="potatopc_135" position={[-0.045, 0.222, -0.013]}>
                  <group
                    name="ssd2_9"
                    position={[0.187, 0.037, -0.124]}
                    rotation={[-0.985, -0.87, -0.856]}
                  >
                    <group
                      name="cube_0"
                      position={[-0.02, 0.115, -0.034]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_7"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_7.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_1"
                      position={[-0.02, 0.115, -0.034]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_9"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_9.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_2"
                      position={[-0.02, 0.115, -0.034]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_11"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_11.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_3"
                      position={[-0.02, 0.115, -0.034]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_13"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_13.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_4"
                      position={[-0.02, 0.115, -0.034]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_15"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_15.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_5"
                      position={[-0.02, 0.115, -0.034]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_17"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_17.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_6"
                      position={[-0.025, 0.159, -0.038]}
                      rotation={[2.793, -0.305, 2.967]}
                    >
                      <mesh
                        name="Object_19"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_19.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_7"
                      position={[-0.025, 0.159, -0.038]}
                      rotation={[2.793, -0.305, 2.967]}
                    >
                      <mesh
                        name="Object_21"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_21.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_8"
                      position={[-0.025, 0.159, -0.038]}
                      rotation={[2.793, -0.305, 2.967]}
                    >
                      <mesh
                        name="Object_23"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_23.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="ssd_19" position={[-0.071, 0.152, -0.18]}>
                    <group
                      name="cube_10"
                      position={[-0.002, -0.004, 0.002]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_26"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_26.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_11"
                      position={[-0.002, -0.004, 0.002]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_28"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_28.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_12"
                      position={[-0.002, -0.004, 0.002]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_30"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_30.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_13"
                      position={[-0.002, -0.004, 0.002]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_32"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_32.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_14"
                      position={[-0.002, -0.004, 0.002]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_34"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_34.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_15"
                      position={[-0.002, -0.004, 0.002]}
                      rotation={[-Math.PI / 9, 0.305, 0.175]}
                    >
                      <mesh
                        name="Object_36"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_36.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_16"
                      position={[-0.007, 0.04, -0.002]}
                      rotation={[2.793, -0.305, 2.967]}
                    >
                      <mesh
                        name="Object_38"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_38.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_17"
                      position={[-0.007, 0.04, -0.002]}
                      rotation={[2.793, -0.305, 2.967]}
                    >
                      <mesh
                        name="Object_40"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_40.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cube_18"
                      position={[-0.007, 0.04, -0.002]}
                      rotation={[2.793, -0.305, 2.967]}
                    >
                      <mesh
                        name="Object_42"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_42.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group
                    name="gpu_73"
                    position={[-0.164, 0.141, 0.004]}
                    rotation={[0.008, -0.413, 0.325]}
                  >
                    <group name="cube_20" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_45"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_45.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_21" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_47"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_47.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_22" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_49"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_49.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_23" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_51"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_51.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_24" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_53"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_53.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_25" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_55"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_55.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_26" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_57"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_57.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_27" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_59"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_59.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_28" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_61"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_61.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_29" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_63"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_63.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_30" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_65"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_65.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_31" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_67"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_67.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_32" position={[-0.007, 0.012, 0.013]}>
                      <mesh
                        name="Object_69"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_69.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_33" position={[-0.007, 0.012, 0.013]}>
                      <mesh
                        name="Object_71"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_71.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_34" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_73"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_73.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_35" position={[-0.007, 0.012, 0.013]}>
                      <mesh
                        name="Object_75"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_75.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_36" position={[-0.007, 0.012, 0.013]}>
                      <mesh
                        name="Object_77"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_77.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_37"
                      position={[-0.007, 0.012, 0.013]}
                      rotation={[0, 0, -2.4]}
                    >
                      <mesh
                        name="Object_79"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_79.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_38"
                      position={[-0.007, 0.012, 0.013]}
                      rotation={[0, 0, -2.4]}
                    >
                      <mesh
                        name="Object_81"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_81.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_39"
                      position={[-0.007, 0.012, 0.013]}
                      rotation={[0, 0, -2.4]}
                    >
                      <mesh
                        name="Object_83"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_83.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_40"
                      position={[-0.007, 0.012, 0.013]}
                      rotation={[0, 0, -2.4]}
                    >
                      <mesh
                        name="Object_85"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_85.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_41" position={[-0.007, 0.012, -0.014]}>
                      <mesh
                        name="Object_87"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_87.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_42" position={[-0.007, 0.012, -0.014]}>
                      <mesh
                        name="Object_89"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_89.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_43" position={[-0.007, 0.012, -0.014]}>
                      <mesh
                        name="Object_91"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_91.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_44"
                      position={[-0.007, 0.012, -0.014]}
                      rotation={[0, 0, -2.4]}
                    >
                      <mesh
                        name="Object_93"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_93.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_45"
                      position={[-0.007, 0.012, -0.014]}
                      rotation={[0, 0, -2.4]}
                    >
                      <mesh
                        name="Object_95"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_95.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_46"
                      position={[-0.007, 0.012, -0.014]}
                      rotation={[0, 0, -2.4]}
                    >
                      <mesh
                        name="Object_97"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_97.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_47"
                      position={[-0.007, 0.012, -0.014]}
                      rotation={[0, 0, -2.4]}
                    >
                      <mesh
                        name="Object_99"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_99.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_48" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_101"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_101.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_49" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_103"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_103.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_50" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_105"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_105.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_51" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_107"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_107.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_52" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_109"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_109.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_53"
                      position={[0.029, 0.045, -0.013]}
                      rotation={[0, 0, -0.829]}
                    >
                      <mesh
                        name="Object_111"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_111.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_54"
                      position={[0.029, 0.045, -0.013]}
                      rotation={[0, 0, -0.829]}
                    >
                      <mesh
                        name="Object_113"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_113.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_55"
                      position={[0.029, 0.045, -0.013]}
                      rotation={[0, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_115"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_115.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_56"
                      position={[0.029, 0.045, -0.013]}
                      rotation={[0, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_117"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_117.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_57"
                      position={[0.029, 0.045, -0.013]}
                      rotation={[0, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_119"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_119.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_58"
                      position={[0.027, -0.008, -0.013]}
                      rotation={[0, 0, -2.662]}
                    >
                      <mesh
                        name="Object_121"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_121.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_59"
                      position={[0.027, -0.008, -0.013]}
                      rotation={[0, 0, -2.662]}
                    >
                      <mesh
                        name="Object_123"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_123.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_60"
                      position={[0.027, -0.008, -0.013]}
                      rotation={[0, 0, -2.662]}
                    >
                      <mesh
                        name="Object_125"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_125.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_61" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_127"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_127.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_62" position={[0.483, 0.07, -0.001]}>
                      <mesh
                        name="Object_129"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_129.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_63"
                      position={[0.052, 0.023, 0.035]}
                      rotation={[-Math.PI, 0, 0.829]}
                    >
                      <mesh
                        name="Object_131"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_131.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_64"
                      position={[0.052, 0.023, 0.035]}
                      rotation={[-Math.PI, 0, 0.829]}
                    >
                      <mesh
                        name="Object_133"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_133.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_65"
                      position={[0.052, 0.023, 0.035]}
                      rotation={[-Math.PI, 0, 0.829]}
                    >
                      <mesh
                        name="Object_135"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_135.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_66"
                      position={[0.052, 0.023, 0.035]}
                      rotation={[-Math.PI, 0, 0.829]}
                    >
                      <mesh
                        name="Object_137"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_137.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_67"
                      position={[-0.03, 0.062, 0.01]}
                      rotation={[-Math.PI, 0, 2.4]}
                    >
                      <mesh
                        name="Object_139"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_139.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_68"
                      position={[-0.03, 0.062, 0.01]}
                      rotation={[-Math.PI, 0, 2.4]}
                    >
                      <mesh
                        name="Object_141"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_141.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_69"
                      position={[0.012, -0.062, 0.01]}
                      rotation={[-Math.PI, 0, Math.PI / 6]}
                    >
                      <mesh
                        name="Object_143"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_143.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_70"
                      position={[0.035, -0.072, 0.01]}
                      rotation={[-Math.PI, 0, Math.PI / 6]}
                    >
                      <mesh
                        name="Object_145"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_145.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_71"
                      position={[-0.013, -0.057, 0.01]}
                      rotation={[-Math.PI, 0, Math.PI / 6]}
                    >
                      <mesh
                        name="Object_147"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_147.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_72"
                      position={[0.012, -0.069, 0.01]}
                      rotation={[-Math.PI, 0, Math.PI / 6]}
                    >
                      <mesh
                        name="Object_149"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_149.geometry}
                        material={materials.material_1}
                      />
                    </group>
                  </group>
                  <group name="usb_79" position={[0.045, -0.222, 0.013]}>
                    <group name="cube_74">
                      <mesh
                        name="Object_152"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_152.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_75">
                      <mesh
                        name="Object_154"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_154.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group
                      name="cube_76"
                      position={[-0.265, 0.156, 0.138]}
                      rotation={[0.102, 0.241, 1.166]}
                    >
                      <mesh
                        name="Object_156"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_156.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group
                      name="cube_77"
                      position={[0.187, -0.011, 0.002]}
                      rotation={[3.091, 0.121, -1.175]}
                    >
                      <mesh
                        name="Object_158"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_158.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group
                      name="cube_78"
                      position={[-0.106, 0.287, -0.069]}
                      rotation={[0, -0.436, 0]}
                    >
                      <mesh
                        name="Object_160"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_160.geometry}
                        material={materials.material_2}
                      />
                    </group>
                  </group>
                  <group name="cable1_82" position={[0.287, -0.029, 0.091]}>
                    <group name="cube_80" rotation={[0.217, -0.432, 0.397]}>
                      <mesh
                        name="Object_163"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_163.geometry}
                        material={materials.material_3}
                      />
                    </group>
                    <group
                      name="cube_81"
                      position={[-0.25, 0.069, -0.301]}
                      rotation={[-1.732, -0.472, 0.719]}
                    >
                      <mesh
                        name="Object_165"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_165.geometry}
                        material={materials.material_3}
                      />
                    </group>
                  </group>
                  <group name="bone_91" position={[0.287, -0.031, 0.091]}>
                    <group name="cube_83" rotation={[0.217, -0.432, 0.397]}>
                      <mesh
                        name="Object_168"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_168.geometry}
                        material={materials.material_4}
                      />
                    </group>
                    <group name="cube_84" rotation={[0.217, -0.432, 0.397]}>
                      <mesh
                        name="Object_170"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_170.geometry}
                        material={materials.material_4}
                      />
                    </group>
                    <group name="cube_85" rotation={[0.217, -0.432, 0.397]}>
                      <mesh
                        name="Object_172"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_172.geometry}
                        material={materials.material_4}
                      />
                    </group>
                    <group name="cube_86" rotation={[0.217, -0.432, 0.397]}>
                      <mesh
                        name="Object_174"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_174.geometry}
                        material={materials.material_4}
                      />
                    </group>
                    <group
                      name="cube_87"
                      position={[0.001, 0.002, 0.001]}
                      rotation={[0.217, -0.432, 0.397]}
                    >
                      <mesh
                        name="Object_176"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_176.geometry}
                        material={materials.material_4}
                      />
                    </group>
                    <group
                      name="cube_88"
                      position={[0.047, 0.002, 0.023]}
                      rotation={[0.217, -0.432, 0.877]}
                    >
                      <mesh
                        name="Object_178"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_178.geometry}
                        material={materials.material_4}
                      />
                    </group>
                    <group
                      name="cube_89"
                      position={[0.04, 0.029, 0.025]}
                      rotation={[0.217, -0.432, -0.083]}
                    >
                      <mesh
                        name="Object_180"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_180.geometry}
                        material={materials.material_4}
                      />
                    </group>
                    <group
                      name="cube_90"
                      position={[0.001, 0.002, 0.001]}
                      rotation={[0.217, -0.432, 0.397]}
                    >
                      <mesh
                        name="Object_182"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_182.geometry}
                        material={materials.material_4}
                      />
                    </group>
                  </group>
                  <group
                    name="cpu_111"
                    position={[0.045, -0.028, 0.236]}
                    rotation={[-1.889, 0.141, -3.046]}
                  >
                    <group
                      name="cube_92"
                      position={[0, -0.006, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    >
                      <mesh
                        name="Object_185"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_185.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_93"
                      position={[0, -0.006, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    >
                      <mesh
                        name="Object_187"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_187.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_94"
                      position={[-0.066, 0.001, -0.047]}
                      rotation={[-Math.PI / 2, -Math.PI / 4, 0]}
                    >
                      <mesh
                        name="Object_189"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_189.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_95"
                      position={[-0.066, 0.001, -0.047]}
                      rotation={[-Math.PI / 2, -Math.PI / 4, 0]}
                    >
                      <mesh
                        name="Object_191"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_191.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_96"
                      position={[-0.066, 0.001, -0.047]}
                      rotation={[-Math.PI / 2, -Math.PI / 4, 0]}
                    >
                      <mesh
                        name="Object_193"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_193.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_97"
                      position={[-0.066, 0.001, -0.047]}
                      rotation={[-Math.PI / 2, -Math.PI / 4, 0]}
                    >
                      <mesh
                        name="Object_195"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_195.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_98"
                      position={[0.066, 0.001, -0.047]}
                      rotation={[-Math.PI / 2, Math.PI / 4, 0]}
                    >
                      <mesh
                        name="Object_197"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_197.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_99"
                      position={[0.066, 0.001, -0.047]}
                      rotation={[-Math.PI / 2, Math.PI / 4, 0]}
                    >
                      <mesh
                        name="Object_199"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_199.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_100"
                      position={[0.066, 0.001, -0.047]}
                      rotation={[-Math.PI / 2, Math.PI / 4, 0]}
                    >
                      <mesh
                        name="Object_201"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_201.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_101"
                      position={[0.066, 0.001, -0.047]}
                      rotation={[-Math.PI / 2, Math.PI / 4, 0]}
                    >
                      <mesh
                        name="Object_203"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_203.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_102"
                      position={[0, 0.001, 0]}
                      rotation={[-Math.PI / 4, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_205"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_205.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_103"
                      position={[0, 0.001, 0]}
                      rotation={[-Math.PI / 4, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_207"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_207.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_104"
                      position={[0, 0.001, 0]}
                      rotation={[-Math.PI / 4, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_209"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_209.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_105"
                      position={[0, 0.001, 0]}
                      rotation={[-Math.PI / 4, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_211"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_211.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_106"
                      position={[0, 0.001, 0]}
                      rotation={[-2.356, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_213"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_213.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_107"
                      position={[0, 0.001, 0]}
                      rotation={[-2.356, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_215"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_215.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_108"
                      position={[0, 0.001, 0]}
                      rotation={[-2.356, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_217"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_217.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_109"
                      position={[0, 0.001, 0]}
                      rotation={[-2.356, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_219"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_219.geometry}
                        material={materials.material_5}
                      />
                    </group>
                    <group
                      name="cube_110"
                      position={[0, -0.006, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    >
                      <mesh
                        name="Object_221"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_221.geometry}
                        material={materials.material_5}
                      />
                    </group>
                  </group>
                  <group
                    name="ram4_121"
                    position={[0.084, 0.14, -0.05]}
                    rotation={[-0.216, 0.028, -0.128]}
                  >
                    <group name="cube_112" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_224"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_224.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_113" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_226"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_226.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_114" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_228"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_228.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_115" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_230"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_230.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_116" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_232"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_232.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_117" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_234"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_234.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group
                      name="cube_118"
                      position={[0.017, -0.216, 0.008]}
                      rotation={[-Math.PI, 0, 0]}
                    >
                      <mesh
                        name="Object_236"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_236.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group
                      name="cube_119"
                      position={[0.017, -0.216, 0.008]}
                      rotation={[-Math.PI, 0, 0]}
                    >
                      <mesh
                        name="Object_238"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_238.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group
                      name="cube_120"
                      position={[0.017, -0.216, 0.008]}
                      rotation={[-Math.PI, 0, 0]}
                    >
                      <mesh
                        name="Object_240"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_240.geometry}
                        material={materials.material_6}
                      />
                    </group>
                  </group>
                  <group
                    name="ram3_131"
                    position={[0.247, 0.149, 0.013]}
                    rotation={[0.119, -0.055, -0.433]}
                  >
                    <group name="cube_122" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_243"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_243.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_123" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_245"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_245.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_124" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_247"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_247.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_125" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_249"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_249.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_126" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_251"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_251.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group name="cube_127" position={[0.017, -0.512, 0]}>
                      <mesh
                        name="Object_253"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_253.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group
                      name="cube_128"
                      position={[0.017, -0.216, 0.008]}
                      rotation={[-Math.PI, 0, 0]}
                    >
                      <mesh
                        name="Object_255"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_255.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group
                      name="cube_129"
                      position={[0.017, -0.216, 0.008]}
                      rotation={[-Math.PI, 0, 0]}
                    >
                      <mesh
                        name="Object_257"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_257.geometry}
                        material={materials.material_6}
                      />
                    </group>
                    <group
                      name="cube_130"
                      position={[0.017, -0.216, 0.008]}
                      rotation={[-Math.PI, 0, 0]}
                    >
                      <mesh
                        name="Object_259"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_259.geometry}
                        material={materials.material_6}
                      />
                    </group>
                  </group>
                  <group name="cuboid_132" position={[0.045, -0.222, 0.013]}>
                    <mesh
                      name="Object_261"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_261.geometry}
                      material={materials.material_7}
                    />
                  </group>
                  <group
                    name="cube_133"
                    position={[-0.045, 0.066, 0.094]}
                    rotation={[0, 0.218, 0]}
                  >
                    <mesh
                      name="Object_263"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_263.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cube_134"
                    position={[-0.064, 0.045, -0.195]}
                    rotation={[1.532, -0.665, 2.342]}
                  >
                    <mesh
                      name="Object_265"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_265.geometry}
                      material={materials.material_9}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
}

useGLTF.preload("/potato_pc.glb");

export default Potato;



